### ISSUE TITLE
visualizer problem

### ISSUE THREAD

**Issue by ForestWang** [hustvl/SparseInst#17]
File "/root/work/detectron2/detectron2/utils/visualizer.py", line 96, in __init__
    raise ValueError("GenericMask cannot handle object {} of type '{}'".format(m, type(m)))
ValueError: GenericMask cannot handle object tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]]) of type '<class 'torch.Tensor'>'

report a problem with Detectron2 master version

**Comment by ForestWang** [comment]
seems with the setting 'MASK_FORMAT', my training set it to polygon. the same own data with setting to 'botmask' training with solov2, no issue occured when predict. so what's the difference between 'polygon' and 'bitmask' for detectron2

**Comment by wondervictor** [comment]
Hi @ForestWang, thanks for your interest in SparseInst.
As for the first problem, it's due to the differences between versions of detectron2. You can refer to the former issue #10, specifically, this comment: https://github.com/hustvl/SparseInst/issues/10#issuecomment-1090173630.
For the second problem about the `mask_format`: `polygon` and `bitmasks`: detectron2 provides 2 formats to store the object masks, *i.e.,* `polygon` by the points (`x,y`) of the contours or the `bitmasks` by the `HxW` binary tensor. Compared to `bitmasks`, the `polygon` format is more convenient for transformations, *e.g.,* cropping and translation. We adopt `bitmasks` as the default format.

**Comment by ForestWang** [comment]
thanks very much.
