### ISSUE TITLE
Performance on RTX 3090 very slow

### ISSUE THREAD

**Issue by divgill91** [hustvl/SparseInst#32]
Running demo.py on a single image and getting 0.98s to detect 3 instances 

This seems very very slow to me.

Running code in WSL2 with cuda 11.3 with pytorch 1.10

Running the sparse_inst_r50_giam_aug_2b7d68.pth model.

When I isolate just the prediction step I get Pred Time:  0.25752179622650145 which is still very slow

I am using torch.cuda.synchronize() as well as doing some prediction calls before the timing loop to allocate GPU memory, etc.

I know the model is capable of more speed so it must be my setup but I have tested other models that turn much faster such as Yolact

**Comment by wondervictor** [comment]
Hi @divgill91, thank you for your interest in SparseInst. This problem is due to the slow visualization and image loading procedures, and you can refer to https://github.com/hustvl/SparseInst/issues/11#issuecomment-1092409408
For measuring accurate speed, we recommend you to use `test_net.py` for inference and evaluation.

**Comment by divgill91** [comment]
Turns out the issue was that I was not resizing my input image to a smaller size. Sizes around 640x480 give me the desired FPS

Thanks
