### ISSUE TITLE
custom training

### ISSUE THREAD

**Issue by kirkdort44** [hustvl/SparseInst#34]
Hello,

I want to do custom training, but I want to do it on this pretrained model.
For this, I need to change which values in config.py.

I have 2 class

Thanks.

Note : 
What i did : 
    cfg.MODEL.SPARSE_INST.DECODER.NUM_MASKS = 2#100
    cfg.MODEL.SPARSE_INST.DECODER.NUM_CLASSES = 2#80 
but it didn't work well

**Comment by wondervictor** [comment]
Hi @kirkdort44, thank you for your interest in SparseInst. If you have only 2 classes, you only need to change `cfg.MODEL.SPARSE_INST.DECODER.NUM_CLASSES ` to 2. The `NUM_MASKS` determines the maximum instances in each image. In addition, you need to remove the weights of the `classifier` or `pred_scores` in the pre-trained models, since the classification layer outputs 80 classes.

**Comment by kirkdort44** [comment]
Thank you so so much for your answer. 

I have downloaded pretrained model from your page. And then i have change Model.WEIGHTS in Base-SparseInst.yaml
Model :
    WEIGHTS :SparseInst/weights/sparse_inst_r50_base_ff9809.pth"

Is It enough?

Thanks

**Comment by wondervictor** [comment]
Since you only segment instances of 2 classes, you need to reduce the `NUM_CLASSES` to 2 and remove the weights of `pred_scores` in the checkpoints or it will throw an error about the mismatch of loading parameters.

**Comment by kirkdort44** [comment]
Thank you so much , Do you have any suggestions, how can I do this?

**Comment by kirkdort44** [comment]
Thank you

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
