### ISSUE TITLE
question about Group-IAM

### ISSUE THREAD

**Issue by eremo2002** [hustvl/SparseInst#43]
Hi author! thanks for your nice work.

I trained SparseInst for instance segmentation in my custom dataset and got nice performance. 

But I have some questions about IAM.

My dataset is single class and there are 2 instances per image. (All images have 2 objects)

Inference results are good, but sometimes there are very small outlier masks.

I thought maybe this is because group instance activation maps. 

To remove outlier masks, is it helpful to change GROUPS value to 1?

Initial config settings
SPARSE_INST:
    CLS_THRESHOLD: 0.5
    DATASET_MAPPER: SparseInstDatasetMapper
    DECODER:
      **GROUPS: 4**
      INST:
        CONVS: 4
        DIM: 256
      KERNEL_DIM: 128
      MASK:
        CONVS: 4
        DIM: 256
      NAME: GroupIAMDecoder
      **NUM_CLASSES: 1**
      **NUM_MASKS: 2**
      
Thank you.

**Comment by wondervictor** [comment]
Hi @eremo2002, thanks for your interest in SparseInst : )
We have two hyper-parameters for IAM, i.e., `NUM_MASKS` determines the maximum number of instances in the image while `GROUPS` determines the number of group activation maps for each instance.
In your setting, `NUM_MASKS` can be set to 2 since each image contains 2 objects, while you can increase the `GROUPS` for more accurate segmentation results.
`GROUPS` does not affect the number of detected instances.

**Comment by eremo2002** [comment]
Ok, I will try it.
Thank you!

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
