### ISSUE TITLE
is it okay to run model without NMS process?

### ISSUE THREAD

**Issue by chansunsong** [hustvl/SparseInst#68]
Hi, Thank you for your great work.

 I have a question about effect of no NMS process.
If I change class_threshold 0.05 to 0.3, pretrained model result which is obtained by sparse_inst_r50vd_dcn_giam_aug model changes AP:37.6, AR: 47.5 to AP: 35.1 AR: 40.3 
I think Dropped AP  is strange. I guess Inference without NMS process is reason.
Please tell me about the reason.

**Comment by wondervictor** [comment]
Hi @chansunsong, thanks for your interest in SparseInst!
NMS has little impact on SparseInst for duplicate removal. SparseInst adopts the one-to-one assignment which forces one ground-truth object to match only one predicted object. Exactly, adding NMS to SparseInst will not improve the performance. 
However, directly lowering the threshold will remove many positive predictions. In my opinion, this degradation is not due to the NMS.

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
