### ISSUE TITLE
how to improve the inference speed?

### ISSUE THREAD

**Issue by SiChuanJay** [hustvl/SparseInst#78]
Hello, thanks for your work, it is very good. I want to train a model with my dataset, and it has only one category. I need to deploy the model on CPU device and has real-time speed. At present, I have changed the bankbone to mobilenetv3, but it is not enough. So, can you give me some advice?  Thank you very much!

**Comment by wondervictor** [comment]
Hi @SiChuanJay, thanks for your interest in SparseInst!
As for accelerating SparseInst on CPU devices, you can try:
* reduce the layers in the decoder, e.g., using 2 convolutions instead of 4 convolutions,
* replace the 3x3 convolutions with depthwise 3x3 convolutions with 1x1 convolutions (point-wise and depthwise),
If you make any progress, could you share us with your work on deploying SparseInst on CPU?

**Comment by SiChuanJay** [comment]
@wondervictor Hi, thanks for your advice, but our project achieved faster speeds and better results on Solov2, so we suspended work on sparseInst. But sparseInst is still a good model and has given me a lot of inspiration. Thank you very much.

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about SparseInst in the future, you're welcome to open a new issue.
